### ISSUE TITLE
주간 보고 (2022.11.26)

### ISSUE THREAD

**Issue by hyunmin0317** [hyunmin0317/SOM-FE#15]
### DONE
- [x] 카카오톡 로그인
- [x] 마이페이지 (사용자 이름, 프로필 사진, 성인 인증)
- [x] 게임 종료 시 결과 화면 추가
- [x] 백도 에러 해결  
<br>

### TODO
- [ ] 백엔드 질문 API 적용
- [ ] 프론트 디자인 수정
    - [ ] 말 크기 조정
    - [ ] 화면 비율 수정
    - [ ] 플레이어 선택 가독성 향상
