### ISSUE TITLE
주간 보고 (2022.09.24)

### ISSUE THREAD

**Issue by hyunmin0317** [hyunmin0317/SOM-FE#2]
### DONE
- [x] 로그인 하기 전 게임설명화면이 너무 짧게 지나감. 
    - 기존 1초에서 3초로 딜레이 수정
- [x] 현재 게임 화면 중간 빨간색 카드를 클릭하면 말이 추가되는 방식인데, 본인 순서 확인이 어려움, 또, 윷놀이 할 때 같은 말이 계속 움직일 수도 있고, 새로운 말로 시작할 수도 있는데, 선택하기가 쉽지 않음 
    -> 플레이어 클릭하고, 말을 선택할 수 있도록 바꾸면 좋을 듯. 
   - 본인 순서 확인 추가
      ![image](https://user-images.githubusercontent.com/63601183/192084804-567e6586-75b4-496d-8941-e8b2a35980d2.png)
- [x] 말이 말을 잡으면 리액션이 있었으면 좋겠음(환호한다거나 박수를 쳐준다거나)
   - [ ] 디자인 개선 필요함
       ![image](https://user-images.githubusercontent.com/63601183/192085550-afe90990-2aef-487e-867e-45f0dad5013b.png)
<br>

### TODO
- [ ]  게임진행방법에 대한 설명이 필요. 게임 화면 중에서도 클릭하면 볼 수 있도록 하는 메뉴 필요
- [ ] 플레이어 캐릭터와 윷놀이 말과 분리가 필요함. -> 플레이어 캐릭터 선택 메뉴 필요
<br>

### BE & UI
- [ ] 배경화면에 나무등을 추가해 조금더 화면이 풍성한 느낌을 주면 좋겠음.
   - 디자인 지원이 필요함 
- [ ] 게임질문 DB에 입력을 다하시면 FW팀에게 파일(엑셀파일이라고 들었습니다)한번 보내주시고 거기에 저희가 질문을 추가하거나 문장을 수정할 수 있는지 궁금합니다. 
   - 백엔드 지원이 필요함
   - 스프링의 경우 관리자 페이지가 존재하지 않아 따로 admin 페이지 개발이 필요하므로 어려움 (장고의 경우 가능)
<br>

### DEFER
- [ ] 플레이어 선택 메뉴가 필요함 -> 1인, 2인, 3인 이상 선택할 수 있도록 수정 
    - 2인용 게임으로 설계하여 지금와서 수정이 매우 어려움
